"""add anomaly detection fields

Revision ID: 58f6b38c38d4
Revises: c0b926100963
Create Date: 2026-09-15 17:47:53.162466

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58f6b38c38d4"
down_revision: str | Sequence[str] | None = "c0b926100963"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("monitor_checks", sa.Column("is_anomaly", sa.Boolean(), nullable=False))
    op.add_column("monitor_checks", sa.Column("anomaly_score", sa.Float(), nullable=True))
    op.add_column("monitor_checks", sa.Column("anomaly_reason", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_monitor_checks_is_anomaly"), "monitor_checks", ["is_anomaly"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monitor_checks_is_anomaly"), table_name="monitor_checks")
    op.drop_column("monitor_checks", "anomaly_reason")
    op.drop_column("monitor_checks", "anomaly_score")
    op.drop_column("monitor_checks", "is_anomaly")
    # ### end Alembic commands ###
