"""add notification preferences

Revision ID: 66384dace6de
Revises: 58f6b38c38d4
Create Date: 2026-09-15 20:11:27.417713

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66384dace6de"
down_revision: str | Sequence[str] | None = "58f6b38c38d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_address", sa.String(length=320), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("notify_on_downtime", sa.Boolean(), nullable=False),
        sa.Column("notify_on_recovery", sa.Boolean(), nullable=False),
        sa.Column("notify_on_anomaly", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_preferences")
    # ### end Alembic commands ###
