"""add notification ownership

Revision ID: 6cc66832963a
Revises: be6cf83696a8
Create Date: 2026-09-16 03:31:58.324079

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cc66832963a"
down_revision: str | Sequence[str] | None = "be6cf83696a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_preferences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_notification_preferences_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notification_preferences_user_id"), ["user_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_notification_preferences_user_id_users",
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("websites", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_websites_user_id_users",
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("websites", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(
            "fk_notification_preferences_user_id_users",
            type_="foreignkey",
        )

    with op.batch_alter_table("notification_preferences", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(
            "fk_websites_user_id_users",
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_notification_preferences_user_id"))
        batch_op.drop_index(batch_op.f("ix_notification_preferences_id"))
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
