"""add monitor checks table

Revision ID: 81a50d0d6893
Revises: 22aa1345db99
Create Date: 2026-09-15 15:26:23.169697

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81a50d0d6893"
down_revision: str | Sequence[str] | None = "22aa1345db99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_websites_id"), table_name="websites")
    op.drop_index(op.f("ix_websites_url"), table_name="websites")
    op.drop_table("websites")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "websites",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=120), nullable=False),
        sa.Column("url", sa.VARCHAR(length=500), nullable=False),
        sa.Column("check_interval_minutes", sa.INTEGER(), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_websites_url"), "websites", ["url"], unique=1)
    op.create_index(op.f("ix_websites_id"), "websites", ["id"], unique=False)
    # ### end Alembic commands ###
