"""add website ownership

Revision ID: be6cf83696a8
Revises: 000cd1a0793f
Create Date: 2026-09-16 03:05:31.369889

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be6cf83696a8"
down_revision: str | Sequence[str] | None = "000cd1a0793f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("websites", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_websites_url"))
        batch_op.create_index(batch_op.f("ix_websites_url"), ["url"], unique=False)
        batch_op.create_index(batch_op.f("ix_websites_user_id"), ["user_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_websites_owner_id_users",
            "users",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("websites", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_websites_user_id"))
        batch_op.drop_index(batch_op.f("ix_websites_url"))
        batch_op.create_index(batch_op.f("ix_websites_url"), ["url"], unique=1)
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
